name: chotanews
description: "A New Flutter project."
publish_to: 'none'
version: 5.0.5+2152
environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  share_plus: ^10.1.4
  another_flushbar: ^1.12.30
  flutter_svg: ^2.0.17
  flutter_screenutil: ^5.9.3
  dio: ^5.8.0+1
  video_player: ^2.9.2
  youtube_player_flutter: ^9.1.1
  carousel_slider: ^5.0.0
  flutter_card_swiper: ^7.0.2
  firebase_auth: ^5.4.1
  firebase_core: ^3.13.0
  shared_preferences: ^2.4.0
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  webengage_flutter: ^1.6.0
  firebase_messaging: ^15.2.5
  flutter_otp_text_field: ^1.4.0+2
  smooth_page_indicator: ^1.2.0+3
  permission_handler: ^11.3.1
  rxdart: ^0.28.0
  google_fonts: ^6.2.1
  provider: ^6.1.2
  flutter_linkify: ^6.0.0
  http: ^1.3.0
  flutter_launcher_icons: ^0.14.3
  screenshot: ^3.0.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  geolocator: ^13.0.2
  pin_code_fields: ^8.0.1
  easy_url_launcher: ^0.0.7
  geocoding: ^3.0.0
  google_mobile_ads: ^5.3.1
  firebase_analytics: ^11.4.4
  facebook_app_events: ^0.19.5
  package_info_plus: ^8.3.0
  app_links: ^6.4.0
  image_picker: ^1.1.2
  easy_localization: ^3.0.7+1
  flutter_inappwebview: ^6.1.5
  app_tracking_transparency: ^2.0.6+1
  shimmer: ^3.0.0
  go_router: ^14.8.1
  file_picker: ^10.1.2
  http_parser: ^4.1.2
  infinite_scroll_pagination: ^5.0.0
  extended_image: ^9.1.0
  flutter_swiper_view: ^1.1.8
  platform_device_id_plus: ^1.0.7
  device_info_plus: ^11.3.0
  new_version_plus: ^0.1.0
  in_app_update: ^4.2.3
  flutter_install_referrer: ^2.0.2
  flutter_upgrade_version: ^1.1.8
  firebase_crashlytics: ^4.3.6
  timeago: ^3.7.1
  lottie: ^3.3.1
  animated_rating_stars: ^1.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  workmanager: ^0.6.0
  cron: ^0.6.2
  android_play_install_referrer: ^0.4.0
  intl: ^0.20.2




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15

flutter:

  uses-material-design: true



  assets:
    - assets/translations/en.json
    - assets/translations/te.json
    - assets/translations/hi.json
    - assets/svg/Chota_news_logo.svg
    - assets/svg/logo_ChotaNews_black.svg
    - assets/svg/indianFlag.svg
    - assets/
    - assets/images/
    - assets/icons/
    - assets/settings_icons/
    - assets/new_app_icon/
    - assets/svg/
    - assets/svg/Profile.svg
    - assets/svg/new_refresh.svg
    - assets/svg/new_comment.svg
    - shorebird.yaml


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/playstore.png"