
// ✅ Keep buildscript at the top
buildscript {
    ext.kotlin_version = '2.1.0'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.android.tools.build:gradle:8.2.2' // Updated to latest stable Gradle version
        classpath 'com.google.gms:google-services:4.4.2' // Google services plugin
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}




//// ✅ Move plugins AFTER buildscript
//plugins {
//    id 'com.android.application' version '8.2.1' apply false
//    id 'org.jetbrains.kotlin.android' version '1.9.0' apply false
//}
//
//
//
//allprojects {
//    repositories {
//        google()
//        mavenCentral()
//        maven { url 'https://webengage.bintray.com/android' }
//    }
//}
//
//rootProject.buildDir = "../build"
//subprojects {
//    project.buildDir = "${rootProject.buildDir}/${project.name}"
//}
//
//tasks.register("clean", Delete) {
//    delete rootProject.buildDir
//}
